title: jsacks
author: memememe
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Yeah whateve

# social links
twitter_username: jasonsacks
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
